#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABP_Player

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "AnimGraphRuntime_structs.hpp"


namespace SDK
{

// ScriptStruct ABP_Player.ABP_Player_C.AnimBlueprintGeneratedConstantData
// 0x023F (0x0240 - 0x0001)
struct ABP_Player::FAnimBlueprintGeneratedConstantData final : public FAnimBlueprintConstantData
{
public:
	uint8                                         Pad_3B82[0x3];                                     // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class FName                                   __NameProperty_1320;                               // 0x0004(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_1321;                               // 0x000C(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_1322;                               // 0x0014(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_1323;                               // 0x001C(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_1324;                               // 0x0024(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_1325;                               // 0x002C(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_1326;                               // 0x0034(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3B83[0x4];                                     // 0x003C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<float>                                 __ArrayProperty_1327;                              // 0x0040(0x0010)(BlueprintVisible, EditFixedSize)
	EAlphaBlendOption                             __EnumProperty_1328;                               // 0x0050(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3B84[0x7];                                     // 0x0051(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<float>                                 __ArrayProperty_1329;                              // 0x0058(0x0010)(BlueprintVisible, EditFixedSize)
	ERefPoseType                                  __ByteProperty_1330;                               // 0x0068(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3B85[0x7];                                     // 0x0069(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<float>                                 __ArrayProperty_1331;                              // 0x0070(0x0010)(BlueprintVisible, EditFixedSize)
	class FName                                   __NameProperty_1332;                               // 0x0080(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_1333;                               // 0x0088(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         __IntProperty_1334;                                // 0x0090(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_1335;                               // 0x0094(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         __IntProperty_1336;                                // 0x009C(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_1337;                               // 0x00A0(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         __IntProperty_1338;                                // 0x00A8(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_1339;                               // 0x00AC(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         __IntProperty_1340;                                // 0x00B4(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_1341;                               // 0x00B8(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         __IntProperty_1342;                                // 0x00C0(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_1343;                               // 0x00C4(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         __IntProperty_1344;                                // 0x00CC(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_1345;                               // 0x00D0(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         __IntProperty_1346;                                // 0x00D8(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_1347;                               // 0x00DC(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         __IntProperty_1348;                                // 0x00E4(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_1349;                               // 0x00E8(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         __IntProperty_1350;                                // 0x00F0(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_1351;                               // 0x00F4(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         __IntProperty_1352;                                // 0x00FC(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_1353;                               // 0x0100(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         __IntProperty_1354;                                // 0x0108(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3B86[0x4];                                     // 0x010C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UBlendProfile*                          __BlendProfile_1355;                               // 0x0110(0x0008)(BlueprintVisible, ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	class UCurveFloat*                            __CurveFloat_1356;                                 // 0x0118(0x0008)(BlueprintVisible, ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	EAlphaBlendOption                             __EnumProperty_1357;                               // 0x0120(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EBlendListTransitionType                      __EnumProperty_1358;                               // 0x0121(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3B87[0x6];                                     // 0x0122(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<float>                                 __ArrayProperty_1359;                              // 0x0128(0x0010)(BlueprintVisible, EditFixedSize)
	bool                                          __BoolProperty_1360;                               // 0x0138(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3B88[0x3];                                     // 0x0139(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         __FloatProperty_1361;                              // 0x013C(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FInputScaleBiasClampConstants          __StructProperty_1362;                             // 0x0140(0x002C)(BlueprintVisible, NoDestructor)
	float                                         __FloatProperty_1363;                              // 0x016C(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          __BoolProperty_1364;                               // 0x0170(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EAnimSyncMethod                               __EnumProperty_1365;                               // 0x0171(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EAnimGroupRole                                __ByteProperty_1366;                               // 0x0172(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3B89[0x1];                                     // 0x0173(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	class FName                                   __NameProperty_1367;                               // 0x0174(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_1368;                               // 0x017C(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         __IntProperty_1369;                                // 0x0184(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FAnimNodeFunctionRef                   __StructProperty_1370;                             // 0x0188(0x0020)(BlueprintVisible, NoDestructor)
	struct FAnimSubsystem_PropertyAccess          AnimBlueprintExtension_PropertyAccess;             // 0x01A8(0x0080)()
	struct FAnimSubsystem_Base                    AnimBlueprintExtension_Base;                       // 0x0228(0x0018)()
};
static_assert(alignof(ABP_Player::FAnimBlueprintGeneratedConstantData) == 0x000008, "Wrong alignment on ABP_Player::FAnimBlueprintGeneratedConstantData");
static_assert(sizeof(ABP_Player::FAnimBlueprintGeneratedConstantData) == 0x000240, "Wrong size on ABP_Player::FAnimBlueprintGeneratedConstantData");
static_assert(offsetof(ABP_Player::FAnimBlueprintGeneratedConstantData, __NameProperty_1320) == 0x000004, "Member 'ABP_Player::FAnimBlueprintGeneratedConstantData::__NameProperty_1320' has a wrong offset!");
static_assert(offsetof(ABP_Player::FAnimBlueprintGeneratedConstantData, __NameProperty_1321) == 0x00000C, "Member 'ABP_Player::FAnimBlueprintGeneratedConstantData::__NameProperty_1321' has a wrong offset!");
static_assert(offsetof(ABP_Player::FAnimBlueprintGeneratedConstantData, __NameProperty_1322) == 0x000014, "Member 'ABP_Player::FAnimBlueprintGeneratedConstantData::__NameProperty_1322' has a wrong offset!");
static_assert(offsetof(ABP_Player::FAnimBlueprintGeneratedConstantData, __NameProperty_1323) == 0x00001C, "Member 'ABP_Player::FAnimBlueprintGeneratedConstantData::__NameProperty_1323' has a wrong offset!");
static_assert(offsetof(ABP_Player::FAnimBlueprintGeneratedConstantData, __NameProperty_1324) == 0x000024, "Member 'ABP_Player::FAnimBlueprintGeneratedConstantData::__NameProperty_1324' has a wrong offset!");
static_assert(offsetof(ABP_Player::FAnimBlueprintGeneratedConstantData, __NameProperty_1325) == 0x00002C, "Member 'ABP_Player::FAnimBlueprintGeneratedConstantData::__NameProperty_1325' has a wrong offset!");
static_assert(offsetof(ABP_Player::FAnimBlueprintGeneratedConstantData, __NameProperty_1326) == 0x000034, "Member 'ABP_Player::FAnimBlueprintGeneratedConstantData::__NameProperty_1326' has a wrong offset!");
static_assert(offsetof(ABP_Player::FAnimBlueprintGeneratedConstantData, __ArrayProperty_1327) == 0x000040, "Member 'ABP_Player::FAnimBlueprintGeneratedConstantData::__ArrayProperty_1327' has a wrong offset!");
static_assert(offsetof(ABP_Player::FAnimBlueprintGeneratedConstantData, __EnumProperty_1328) == 0x000050, "Member 'ABP_Player::FAnimBlueprintGeneratedConstantData::__EnumProperty_1328' has a wrong offset!");
static_assert(offsetof(ABP_Player::FAnimBlueprintGeneratedConstantData, __ArrayProperty_1329) == 0x000058, "Member 'ABP_Player::FAnimBlueprintGeneratedConstantData::__ArrayProperty_1329' has a wrong offset!");
static_assert(offsetof(ABP_Player::FAnimBlueprintGeneratedConstantData, __ByteProperty_1330) == 0x000068, "Member 'ABP_Player::FAnimBlueprintGeneratedConstantData::__ByteProperty_1330' has a wrong offset!");
static_assert(offsetof(ABP_Player::FAnimBlueprintGeneratedConstantData, __ArrayProperty_1331) == 0x000070, "Member 'ABP_Player::FAnimBlueprintGeneratedConstantData::__ArrayProperty_1331' has a wrong offset!");
static_assert(offsetof(ABP_Player::FAnimBlueprintGeneratedConstantData, __NameProperty_1332) == 0x000080, "Member 'ABP_Player::FAnimBlueprintGeneratedConstantData::__NameProperty_1332' has a wrong offset!");
static_assert(offsetof(ABP_Player::FAnimBlueprintGeneratedConstantData, __NameProperty_1333) == 0x000088, "Member 'ABP_Player::FAnimBlueprintGeneratedConstantData::__NameProperty_1333' has a wrong offset!");
static_assert(offsetof(ABP_Player::FAnimBlueprintGeneratedConstantData, __IntProperty_1334) == 0x000090, "Member 'ABP_Player::FAnimBlueprintGeneratedConstantData::__IntProperty_1334' has a wrong offset!");
static_assert(offsetof(ABP_Player::FAnimBlueprintGeneratedConstantData, __NameProperty_1335) == 0x000094, "Member 'ABP_Player::FAnimBlueprintGeneratedConstantData::__NameProperty_1335' has a wrong offset!");
static_assert(offsetof(ABP_Player::FAnimBlueprintGeneratedConstantData, __IntProperty_1336) == 0x00009C, "Member 'ABP_Player::FAnimBlueprintGeneratedConstantData::__IntProperty_1336' has a wrong offset!");
static_assert(offsetof(ABP_Player::FAnimBlueprintGeneratedConstantData, __NameProperty_1337) == 0x0000A0, "Member 'ABP_Player::FAnimBlueprintGeneratedConstantData::__NameProperty_1337' has a wrong offset!");
static_assert(offsetof(ABP_Player::FAnimBlueprintGeneratedConstantData, __IntProperty_1338) == 0x0000A8, "Member 'ABP_Player::FAnimBlueprintGeneratedConstantData::__IntProperty_1338' has a wrong offset!");
static_assert(offsetof(ABP_Player::FAnimBlueprintGeneratedConstantData, __NameProperty_1339) == 0x0000AC, "Member 'ABP_Player::FAnimBlueprintGeneratedConstantData::__NameProperty_1339' has a wrong offset!");
static_assert(offsetof(ABP_Player::FAnimBlueprintGeneratedConstantData, __IntProperty_1340) == 0x0000B4, "Member 'ABP_Player::FAnimBlueprintGeneratedConstantData::__IntProperty_1340' has a wrong offset!");
static_assert(offsetof(ABP_Player::FAnimBlueprintGeneratedConstantData, __NameProperty_1341) == 0x0000B8, "Member 'ABP_Player::FAnimBlueprintGeneratedConstantData::__NameProperty_1341' has a wrong offset!");
static_assert(offsetof(ABP_Player::FAnimBlueprintGeneratedConstantData, __IntProperty_1342) == 0x0000C0, "Member 'ABP_Player::FAnimBlueprintGeneratedConstantData::__IntProperty_1342' has a wrong offset!");
static_assert(offsetof(ABP_Player::FAnimBlueprintGeneratedConstantData, __NameProperty_1343) == 0x0000C4, "Member 'ABP_Player::FAnimBlueprintGeneratedConstantData::__NameProperty_1343' has a wrong offset!");
static_assert(offsetof(ABP_Player::FAnimBlueprintGeneratedConstantData, __IntProperty_1344) == 0x0000CC, "Member 'ABP_Player::FAnimBlueprintGeneratedConstantData::__IntProperty_1344' has a wrong offset!");
static_assert(offsetof(ABP_Player::FAnimBlueprintGeneratedConstantData, __NameProperty_1345) == 0x0000D0, "Member 'ABP_Player::FAnimBlueprintGeneratedConstantData::__NameProperty_1345' has a wrong offset!");
static_assert(offsetof(ABP_Player::FAnimBlueprintGeneratedConstantData, __IntProperty_1346) == 0x0000D8, "Member 'ABP_Player::FAnimBlueprintGeneratedConstantData::__IntProperty_1346' has a wrong offset!");
static_assert(offsetof(ABP_Player::FAnimBlueprintGeneratedConstantData, __NameProperty_1347) == 0x0000DC, "Member 'ABP_Player::FAnimBlueprintGeneratedConstantData::__NameProperty_1347' has a wrong offset!");
static_assert(offsetof(ABP_Player::FAnimBlueprintGeneratedConstantData, __IntProperty_1348) == 0x0000E4, "Member 'ABP_Player::FAnimBlueprintGeneratedConstantData::__IntProperty_1348' has a wrong offset!");
static_assert(offsetof(ABP_Player::FAnimBlueprintGeneratedConstantData, __NameProperty_1349) == 0x0000E8, "Member 'ABP_Player::FAnimBlueprintGeneratedConstantData::__NameProperty_1349' has a wrong offset!");
static_assert(offsetof(ABP_Player::FAnimBlueprintGeneratedConstantData, __IntProperty_1350) == 0x0000F0, "Member 'ABP_Player::FAnimBlueprintGeneratedConstantData::__IntProperty_1350' has a wrong offset!");
static_assert(offsetof(ABP_Player::FAnimBlueprintGeneratedConstantData, __NameProperty_1351) == 0x0000F4, "Member 'ABP_Player::FAnimBlueprintGeneratedConstantData::__NameProperty_1351' has a wrong offset!");
static_assert(offsetof(ABP_Player::FAnimBlueprintGeneratedConstantData, __IntProperty_1352) == 0x0000FC, "Member 'ABP_Player::FAnimBlueprintGeneratedConstantData::__IntProperty_1352' has a wrong offset!");
static_assert(offsetof(ABP_Player::FAnimBlueprintGeneratedConstantData, __NameProperty_1353) == 0x000100, "Member 'ABP_Player::FAnimBlueprintGeneratedConstantData::__NameProperty_1353' has a wrong offset!");
static_assert(offsetof(ABP_Player::FAnimBlueprintGeneratedConstantData, __IntProperty_1354) == 0x000108, "Member 'ABP_Player::FAnimBlueprintGeneratedConstantData::__IntProperty_1354' has a wrong offset!");
static_assert(offsetof(ABP_Player::FAnimBlueprintGeneratedConstantData, __BlendProfile_1355) == 0x000110, "Member 'ABP_Player::FAnimBlueprintGeneratedConstantData::__BlendProfile_1355' has a wrong offset!");
static_assert(offsetof(ABP_Player::FAnimBlueprintGeneratedConstantData, __CurveFloat_1356) == 0x000118, "Member 'ABP_Player::FAnimBlueprintGeneratedConstantData::__CurveFloat_1356' has a wrong offset!");
static_assert(offsetof(ABP_Player::FAnimBlueprintGeneratedConstantData, __EnumProperty_1357) == 0x000120, "Member 'ABP_Player::FAnimBlueprintGeneratedConstantData::__EnumProperty_1357' has a wrong offset!");
static_assert(offsetof(ABP_Player::FAnimBlueprintGeneratedConstantData, __EnumProperty_1358) == 0x000121, "Member 'ABP_Player::FAnimBlueprintGeneratedConstantData::__EnumProperty_1358' has a wrong offset!");
static_assert(offsetof(ABP_Player::FAnimBlueprintGeneratedConstantData, __ArrayProperty_1359) == 0x000128, "Member 'ABP_Player::FAnimBlueprintGeneratedConstantData::__ArrayProperty_1359' has a wrong offset!");
static_assert(offsetof(ABP_Player::FAnimBlueprintGeneratedConstantData, __BoolProperty_1360) == 0x000138, "Member 'ABP_Player::FAnimBlueprintGeneratedConstantData::__BoolProperty_1360' has a wrong offset!");
static_assert(offsetof(ABP_Player::FAnimBlueprintGeneratedConstantData, __FloatProperty_1361) == 0x00013C, "Member 'ABP_Player::FAnimBlueprintGeneratedConstantData::__FloatProperty_1361' has a wrong offset!");
static_assert(offsetof(ABP_Player::FAnimBlueprintGeneratedConstantData, __StructProperty_1362) == 0x000140, "Member 'ABP_Player::FAnimBlueprintGeneratedConstantData::__StructProperty_1362' has a wrong offset!");
static_assert(offsetof(ABP_Player::FAnimBlueprintGeneratedConstantData, __FloatProperty_1363) == 0x00016C, "Member 'ABP_Player::FAnimBlueprintGeneratedConstantData::__FloatProperty_1363' has a wrong offset!");
static_assert(offsetof(ABP_Player::FAnimBlueprintGeneratedConstantData, __BoolProperty_1364) == 0x000170, "Member 'ABP_Player::FAnimBlueprintGeneratedConstantData::__BoolProperty_1364' has a wrong offset!");
static_assert(offsetof(ABP_Player::FAnimBlueprintGeneratedConstantData, __EnumProperty_1365) == 0x000171, "Member 'ABP_Player::FAnimBlueprintGeneratedConstantData::__EnumProperty_1365' has a wrong offset!");
static_assert(offsetof(ABP_Player::FAnimBlueprintGeneratedConstantData, __ByteProperty_1366) == 0x000172, "Member 'ABP_Player::FAnimBlueprintGeneratedConstantData::__ByteProperty_1366' has a wrong offset!");
static_assert(offsetof(ABP_Player::FAnimBlueprintGeneratedConstantData, __NameProperty_1367) == 0x000174, "Member 'ABP_Player::FAnimBlueprintGeneratedConstantData::__NameProperty_1367' has a wrong offset!");
static_assert(offsetof(ABP_Player::FAnimBlueprintGeneratedConstantData, __NameProperty_1368) == 0x00017C, "Member 'ABP_Player::FAnimBlueprintGeneratedConstantData::__NameProperty_1368' has a wrong offset!");
static_assert(offsetof(ABP_Player::FAnimBlueprintGeneratedConstantData, __IntProperty_1369) == 0x000184, "Member 'ABP_Player::FAnimBlueprintGeneratedConstantData::__IntProperty_1369' has a wrong offset!");
static_assert(offsetof(ABP_Player::FAnimBlueprintGeneratedConstantData, __StructProperty_1370) == 0x000188, "Member 'ABP_Player::FAnimBlueprintGeneratedConstantData::__StructProperty_1370' has a wrong offset!");
static_assert(offsetof(ABP_Player::FAnimBlueprintGeneratedConstantData, AnimBlueprintExtension_PropertyAccess) == 0x0001A8, "Member 'ABP_Player::FAnimBlueprintGeneratedConstantData::AnimBlueprintExtension_PropertyAccess' has a wrong offset!");
static_assert(offsetof(ABP_Player::FAnimBlueprintGeneratedConstantData, AnimBlueprintExtension_Base) == 0x000228, "Member 'ABP_Player::FAnimBlueprintGeneratedConstantData::AnimBlueprintExtension_Base' has a wrong offset!");

// ScriptStruct ABP_Player.ABP_Player_C.AnimBlueprintGeneratedMutableData
// 0x00BF (0x00C0 - 0x0001)
struct ABP_Player::FAnimBlueprintGeneratedMutableData final : public FAnimBlueprintMutableData
{
public:
	bool                                          __BoolProperty;                                    // 0x0001(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          __BoolProperty_0;                                  // 0x0002(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3B8A[0x5];                                     // 0x0003(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<float>                                 __ArrayProperty_1;                                 // 0x0008(0x0010)(BlueprintVisible, EditFixedSize)
	bool                                          __BoolProperty_2;                                  // 0x0018(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          __BoolProperty_3;                                  // 0x0019(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          __BoolProperty_4;                                  // 0x001A(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          __BoolProperty_5;                                  // 0x001B(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         __FloatProperty_6;                                 // 0x001C(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         __FloatProperty_7;                                 // 0x0020(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          __BoolProperty_8;                                  // 0x0024(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          __BoolProperty_9;                                  // 0x0025(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          __BoolProperty_10;                                 // 0x0026(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          __BoolProperty_11;                                 // 0x0027(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         __FloatProperty_12;                                // 0x0028(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         __FloatProperty_13;                                // 0x002C(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         __FloatProperty_14;                                // 0x0030(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         __FloatProperty_15;                                // 0x0034(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          __BoolProperty_16;                                 // 0x0038(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          __BoolProperty_17;                                 // 0x0039(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          __BoolProperty_18;                                 // 0x003A(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          __BoolProperty_19;                                 // 0x003B(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3B8B[0x4];                                     // 0x003C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<float>                                 __ArrayProperty_20;                                // 0x0040(0x0010)(BlueprintVisible, EditFixedSize)
	bool                                          __BoolProperty_21;                                 // 0x0050(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          __BoolProperty_22;                                 // 0x0051(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          __BoolProperty_23;                                 // 0x0052(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          __BoolProperty_24;                                 // 0x0053(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3B8C[0x4];                                     // 0x0054(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<float>                                 __ArrayProperty_25;                                // 0x0058(0x0010)(BlueprintVisible, EditFixedSize)
	bool                                          __BoolProperty_26;                                 // 0x0068(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          __BoolProperty_27;                                 // 0x0069(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          __BoolProperty_28;                                 // 0x006A(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3B8D[0x1];                                     // 0x006B(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         __FloatProperty_29;                                // 0x006C(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         __FloatProperty_30;                                // 0x0070(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         __FloatProperty_31;                                // 0x0074(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         __FloatProperty_32;                                // 0x0078(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          __BoolProperty_33;                                 // 0x007C(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3B8E[0x3];                                     // 0x007D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         __FloatProperty_34;                                // 0x0080(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         __FloatProperty_35;                                // 0x0084(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          __BoolProperty_36;                                 // 0x0088(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3B8F[0x3];                                     // 0x0089(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         __FloatProperty_37;                                // 0x008C(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          __BoolProperty_38;                                 // 0x0090(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          __BoolProperty_39;                                 // 0x0091(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3B90[0x2];                                     // 0x0092(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         __FloatProperty_40;                                // 0x0094(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         __FloatProperty_41;                                // 0x0098(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         __FloatProperty_42;                                // 0x009C(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         __FloatProperty_43;                                // 0x00A0(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         __FloatProperty_44;                                // 0x00A4(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         __FloatProperty_45;                                // 0x00A8(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         __FloatProperty_46;                                // 0x00AC(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         __FloatProperty_47;                                // 0x00B0(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         __FloatProperty_48;                                // 0x00B4(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         __FloatProperty_49;                                // 0x00B8(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          __BoolProperty_50;                                 // 0x00BC(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          __BoolProperty_51;                                 // 0x00BD(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          __BoolProperty_52;                                 // 0x00BE(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          __BoolProperty_53;                                 // 0x00BF(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(ABP_Player::FAnimBlueprintGeneratedMutableData) == 0x000008, "Wrong alignment on ABP_Player::FAnimBlueprintGeneratedMutableData");
static_assert(sizeof(ABP_Player::FAnimBlueprintGeneratedMutableData) == 0x0000C0, "Wrong size on ABP_Player::FAnimBlueprintGeneratedMutableData");
static_assert(offsetof(ABP_Player::FAnimBlueprintGeneratedMutableData, __BoolProperty) == 0x000001, "Member 'ABP_Player::FAnimBlueprintGeneratedMutableData::__BoolProperty' has a wrong offset!");
static_assert(offsetof(ABP_Player::FAnimBlueprintGeneratedMutableData, __BoolProperty_0) == 0x000002, "Member 'ABP_Player::FAnimBlueprintGeneratedMutableData::__BoolProperty_0' has a wrong offset!");
static_assert(offsetof(ABP_Player::FAnimBlueprintGeneratedMutableData, __ArrayProperty_1) == 0x000008, "Member 'ABP_Player::FAnimBlueprintGeneratedMutableData::__ArrayProperty_1' has a wrong offset!");
static_assert(offsetof(ABP_Player::FAnimBlueprintGeneratedMutableData, __BoolProperty_2) == 0x000018, "Member 'ABP_Player::FAnimBlueprintGeneratedMutableData::__BoolProperty_2' has a wrong offset!");
static_assert(offsetof(ABP_Player::FAnimBlueprintGeneratedMutableData, __BoolProperty_3) == 0x000019, "Member 'ABP_Player::FAnimBlueprintGeneratedMutableData::__BoolProperty_3' has a wrong offset!");
static_assert(offsetof(ABP_Player::FAnimBlueprintGeneratedMutableData, __BoolProperty_4) == 0x00001A, "Member 'ABP_Player::FAnimBlueprintGeneratedMutableData::__BoolProperty_4' has a wrong offset!");
static_assert(offsetof(ABP_Player::FAnimBlueprintGeneratedMutableData, __BoolProperty_5) == 0x00001B, "Member 'ABP_Player::FAnimBlueprintGeneratedMutableData::__BoolProperty_5' has a wrong offset!");
static_assert(offsetof(ABP_Player::FAnimBlueprintGeneratedMutableData, __FloatProperty_6) == 0x00001C, "Member 'ABP_Player::FAnimBlueprintGeneratedMutableData::__FloatProperty_6' has a wrong offset!");
static_assert(offsetof(ABP_Player::FAnimBlueprintGeneratedMutableData, __FloatProperty_7) == 0x000020, "Member 'ABP_Player::FAnimBlueprintGeneratedMutableData::__FloatProperty_7' has a wrong offset!");
static_assert(offsetof(ABP_Player::FAnimBlueprintGeneratedMutableData, __BoolProperty_8) == 0x000024, "Member 'ABP_Player::FAnimBlueprintGeneratedMutableData::__BoolProperty_8' has a wrong offset!");
static_assert(offsetof(ABP_Player::FAnimBlueprintGeneratedMutableData, __BoolProperty_9) == 0x000025, "Member 'ABP_Player::FAnimBlueprintGeneratedMutableData::__BoolProperty_9' has a wrong offset!");
static_assert(offsetof(ABP_Player::FAnimBlueprintGeneratedMutableData, __BoolProperty_10) == 0x000026, "Member 'ABP_Player::FAnimBlueprintGeneratedMutableData::__BoolProperty_10' has a wrong offset!");
static_assert(offsetof(ABP_Player::FAnimBlueprintGeneratedMutableData, __BoolProperty_11) == 0x000027, "Member 'ABP_Player::FAnimBlueprintGeneratedMutableData::__BoolProperty_11' has a wrong offset!");
static_assert(offsetof(ABP_Player::FAnimBlueprintGeneratedMutableData, __FloatProperty_12) == 0x000028, "Member 'ABP_Player::FAnimBlueprintGeneratedMutableData::__FloatProperty_12' has a wrong offset!");
static_assert(offsetof(ABP_Player::FAnimBlueprintGeneratedMutableData, __FloatProperty_13) == 0x00002C, "Member 'ABP_Player::FAnimBlueprintGeneratedMutableData::__FloatProperty_13' has a wrong offset!");
static_assert(offsetof(ABP_Player::FAnimBlueprintGeneratedMutableData, __FloatProperty_14) == 0x000030, "Member 'ABP_Player::FAnimBlueprintGeneratedMutableData::__FloatProperty_14' has a wrong offset!");
static_assert(offsetof(ABP_Player::FAnimBlueprintGeneratedMutableData, __FloatProperty_15) == 0x000034, "Member 'ABP_Player::FAnimBlueprintGeneratedMutableData::__FloatProperty_15' has a wrong offset!");
static_assert(offsetof(ABP_Player::FAnimBlueprintGeneratedMutableData, __BoolProperty_16) == 0x000038, "Member 'ABP_Player::FAnimBlueprintGeneratedMutableData::__BoolProperty_16' has a wrong offset!");
static_assert(offsetof(ABP_Player::FAnimBlueprintGeneratedMutableData, __BoolProperty_17) == 0x000039, "Member 'ABP_Player::FAnimBlueprintGeneratedMutableData::__BoolProperty_17' has a wrong offset!");
static_assert(offsetof(ABP_Player::FAnimBlueprintGeneratedMutableData, __BoolProperty_18) == 0x00003A, "Member 'ABP_Player::FAnimBlueprintGeneratedMutableData::__BoolProperty_18' has a wrong offset!");
static_assert(offsetof(ABP_Player::FAnimBlueprintGeneratedMutableData, __BoolProperty_19) == 0x00003B, "Member 'ABP_Player::FAnimBlueprintGeneratedMutableData::__BoolProperty_19' has a wrong offset!");
static_assert(offsetof(ABP_Player::FAnimBlueprintGeneratedMutableData, __ArrayProperty_20) == 0x000040, "Member 'ABP_Player::FAnimBlueprintGeneratedMutableData::__ArrayProperty_20' has a wrong offset!");
static_assert(offsetof(ABP_Player::FAnimBlueprintGeneratedMutableData, __BoolProperty_21) == 0x000050, "Member 'ABP_Player::FAnimBlueprintGeneratedMutableData::__BoolProperty_21' has a wrong offset!");
static_assert(offsetof(ABP_Player::FAnimBlueprintGeneratedMutableData, __BoolProperty_22) == 0x000051, "Member 'ABP_Player::FAnimBlueprintGeneratedMutableData::__BoolProperty_22' has a wrong offset!");
static_assert(offsetof(ABP_Player::FAnimBlueprintGeneratedMutableData, __BoolProperty_23) == 0x000052, "Member 'ABP_Player::FAnimBlueprintGeneratedMutableData::__BoolProperty_23' has a wrong offset!");
static_assert(offsetof(ABP_Player::FAnimBlueprintGeneratedMutableData, __BoolProperty_24) == 0x000053, "Member 'ABP_Player::FAnimBlueprintGeneratedMutableData::__BoolProperty_24' has a wrong offset!");
static_assert(offsetof(ABP_Player::FAnimBlueprintGeneratedMutableData, __ArrayProperty_25) == 0x000058, "Member 'ABP_Player::FAnimBlueprintGeneratedMutableData::__ArrayProperty_25' has a wrong offset!");
static_assert(offsetof(ABP_Player::FAnimBlueprintGeneratedMutableData, __BoolProperty_26) == 0x000068, "Member 'ABP_Player::FAnimBlueprintGeneratedMutableData::__BoolProperty_26' has a wrong offset!");
static_assert(offsetof(ABP_Player::FAnimBlueprintGeneratedMutableData, __BoolProperty_27) == 0x000069, "Member 'ABP_Player::FAnimBlueprintGeneratedMutableData::__BoolProperty_27' has a wrong offset!");
static_assert(offsetof(ABP_Player::FAnimBlueprintGeneratedMutableData, __BoolProperty_28) == 0x00006A, "Member 'ABP_Player::FAnimBlueprintGeneratedMutableData::__BoolProperty_28' has a wrong offset!");
static_assert(offsetof(ABP_Player::FAnimBlueprintGeneratedMutableData, __FloatProperty_29) == 0x00006C, "Member 'ABP_Player::FAnimBlueprintGeneratedMutableData::__FloatProperty_29' has a wrong offset!");
static_assert(offsetof(ABP_Player::FAnimBlueprintGeneratedMutableData, __FloatProperty_30) == 0x000070, "Member 'ABP_Player::FAnimBlueprintGeneratedMutableData::__FloatProperty_30' has a wrong offset!");
static_assert(offsetof(ABP_Player::FAnimBlueprintGeneratedMutableData, __FloatProperty_31) == 0x000074, "Member 'ABP_Player::FAnimBlueprintGeneratedMutableData::__FloatProperty_31' has a wrong offset!");
static_assert(offsetof(ABP_Player::FAnimBlueprintGeneratedMutableData, __FloatProperty_32) == 0x000078, "Member 'ABP_Player::FAnimBlueprintGeneratedMutableData::__FloatProperty_32' has a wrong offset!");
static_assert(offsetof(ABP_Player::FAnimBlueprintGeneratedMutableData, __BoolProperty_33) == 0x00007C, "Member 'ABP_Player::FAnimBlueprintGeneratedMutableData::__BoolProperty_33' has a wrong offset!");
static_assert(offsetof(ABP_Player::FAnimBlueprintGeneratedMutableData, __FloatProperty_34) == 0x000080, "Member 'ABP_Player::FAnimBlueprintGeneratedMutableData::__FloatProperty_34' has a wrong offset!");
static_assert(offsetof(ABP_Player::FAnimBlueprintGeneratedMutableData, __FloatProperty_35) == 0x000084, "Member 'ABP_Player::FAnimBlueprintGeneratedMutableData::__FloatProperty_35' has a wrong offset!");
static_assert(offsetof(ABP_Player::FAnimBlueprintGeneratedMutableData, __BoolProperty_36) == 0x000088, "Member 'ABP_Player::FAnimBlueprintGeneratedMutableData::__BoolProperty_36' has a wrong offset!");
static_assert(offsetof(ABP_Player::FAnimBlueprintGeneratedMutableData, __FloatProperty_37) == 0x00008C, "Member 'ABP_Player::FAnimBlueprintGeneratedMutableData::__FloatProperty_37' has a wrong offset!");
static_assert(offsetof(ABP_Player::FAnimBlueprintGeneratedMutableData, __BoolProperty_38) == 0x000090, "Member 'ABP_Player::FAnimBlueprintGeneratedMutableData::__BoolProperty_38' has a wrong offset!");
static_assert(offsetof(ABP_Player::FAnimBlueprintGeneratedMutableData, __BoolProperty_39) == 0x000091, "Member 'ABP_Player::FAnimBlueprintGeneratedMutableData::__BoolProperty_39' has a wrong offset!");
static_assert(offsetof(ABP_Player::FAnimBlueprintGeneratedMutableData, __FloatProperty_40) == 0x000094, "Member 'ABP_Player::FAnimBlueprintGeneratedMutableData::__FloatProperty_40' has a wrong offset!");
static_assert(offsetof(ABP_Player::FAnimBlueprintGeneratedMutableData, __FloatProperty_41) == 0x000098, "Member 'ABP_Player::FAnimBlueprintGeneratedMutableData::__FloatProperty_41' has a wrong offset!");
static_assert(offsetof(ABP_Player::FAnimBlueprintGeneratedMutableData, __FloatProperty_42) == 0x00009C, "Member 'ABP_Player::FAnimBlueprintGeneratedMutableData::__FloatProperty_42' has a wrong offset!");
static_assert(offsetof(ABP_Player::FAnimBlueprintGeneratedMutableData, __FloatProperty_43) == 0x0000A0, "Member 'ABP_Player::FAnimBlueprintGeneratedMutableData::__FloatProperty_43' has a wrong offset!");
static_assert(offsetof(ABP_Player::FAnimBlueprintGeneratedMutableData, __FloatProperty_44) == 0x0000A4, "Member 'ABP_Player::FAnimBlueprintGeneratedMutableData::__FloatProperty_44' has a wrong offset!");
static_assert(offsetof(ABP_Player::FAnimBlueprintGeneratedMutableData, __FloatProperty_45) == 0x0000A8, "Member 'ABP_Player::FAnimBlueprintGeneratedMutableData::__FloatProperty_45' has a wrong offset!");
static_assert(offsetof(ABP_Player::FAnimBlueprintGeneratedMutableData, __FloatProperty_46) == 0x0000AC, "Member 'ABP_Player::FAnimBlueprintGeneratedMutableData::__FloatProperty_46' has a wrong offset!");
static_assert(offsetof(ABP_Player::FAnimBlueprintGeneratedMutableData, __FloatProperty_47) == 0x0000B0, "Member 'ABP_Player::FAnimBlueprintGeneratedMutableData::__FloatProperty_47' has a wrong offset!");
static_assert(offsetof(ABP_Player::FAnimBlueprintGeneratedMutableData, __FloatProperty_48) == 0x0000B4, "Member 'ABP_Player::FAnimBlueprintGeneratedMutableData::__FloatProperty_48' has a wrong offset!");
static_assert(offsetof(ABP_Player::FAnimBlueprintGeneratedMutableData, __FloatProperty_49) == 0x0000B8, "Member 'ABP_Player::FAnimBlueprintGeneratedMutableData::__FloatProperty_49' has a wrong offset!");
static_assert(offsetof(ABP_Player::FAnimBlueprintGeneratedMutableData, __BoolProperty_50) == 0x0000BC, "Member 'ABP_Player::FAnimBlueprintGeneratedMutableData::__BoolProperty_50' has a wrong offset!");
static_assert(offsetof(ABP_Player::FAnimBlueprintGeneratedMutableData, __BoolProperty_51) == 0x0000BD, "Member 'ABP_Player::FAnimBlueprintGeneratedMutableData::__BoolProperty_51' has a wrong offset!");
static_assert(offsetof(ABP_Player::FAnimBlueprintGeneratedMutableData, __BoolProperty_52) == 0x0000BE, "Member 'ABP_Player::FAnimBlueprintGeneratedMutableData::__BoolProperty_52' has a wrong offset!");
static_assert(offsetof(ABP_Player::FAnimBlueprintGeneratedMutableData, __BoolProperty_53) == 0x0000BF, "Member 'ABP_Player::FAnimBlueprintGeneratedMutableData::__BoolProperty_53' has a wrong offset!");

}

