#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_AIAction_NPCSpawnOtomo

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Pal_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_AIAction_NPCSpawnOtomo.BP_AIAction_NPCSpawnOtomo_C
// 0x0018 (0x0148 - 0x0130)
class UBP_AIAction_NPCSpawnOtomo_C final : public UPalAIActionBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0130(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class AActor*                                 TargetActor;                                       // 0x0138(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	bool                                          IsRutnMode;                                        // 0x0140(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ActionStart(class APawn* ControlledPawn);
	void ActionTick(class APawn* ControlledPawn, float DeltaSeconds);
	void ExecuteUbergraph_BP_AIAction_NPCSpawnOtomo(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_AIAction_NPCSpawnOtomo_C">();
	}
	static class UBP_AIAction_NPCSpawnOtomo_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_AIAction_NPCSpawnOtomo_C>();
	}
};
static_assert(alignof(UBP_AIAction_NPCSpawnOtomo_C) == 0x000008, "Wrong alignment on UBP_AIAction_NPCSpawnOtomo_C");
static_assert(sizeof(UBP_AIAction_NPCSpawnOtomo_C) == 0x000148, "Wrong size on UBP_AIAction_NPCSpawnOtomo_C");
static_assert(offsetof(UBP_AIAction_NPCSpawnOtomo_C, UberGraphFrame) == 0x000130, "Member 'UBP_AIAction_NPCSpawnOtomo_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UBP_AIAction_NPCSpawnOtomo_C, TargetActor) == 0x000138, "Member 'UBP_AIAction_NPCSpawnOtomo_C::TargetActor' has a wrong offset!");
static_assert(offsetof(UBP_AIAction_NPCSpawnOtomo_C, IsRutnMode) == 0x000140, "Member 'UBP_AIAction_NPCSpawnOtomo_C::IsRutnMode' has a wrong offset!");

}

