#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ActionSoundReaction

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Pal_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_ActionSoundReaction.BP_ActionSoundReaction_C
// 0x0010 (0x0150 - 0x0140)
class UBP_ActionSoundReaction_C final : public UPalActionBase
{
public:
	uint8                                         Pad_3E13[0x8];                                     // 0x0138(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0140(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_BP_ActionSoundReaction(int32 EntryPoint);
	void OnBeginAction();
	void OnEndAction();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_ActionSoundReaction_C">();
	}
	static class UBP_ActionSoundReaction_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_ActionSoundReaction_C>();
	}
};
static_assert(alignof(UBP_ActionSoundReaction_C) == 0x000010, "Wrong alignment on UBP_ActionSoundReaction_C");
static_assert(sizeof(UBP_ActionSoundReaction_C) == 0x000150, "Wrong size on UBP_ActionSoundReaction_C");
static_assert(offsetof(UBP_ActionSoundReaction_C, UberGraphFrame) == 0x000140, "Member 'UBP_ActionSoundReaction_C::UberGraphFrame' has a wrong offset!");

}

