#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_AIAction_WildLife

#include "Basic.hpp"

#include "BP_AIAction_WildLife_classes.hpp"
#include "BP_AIAction_WildLife_parameters.hpp"


namespace SDK
{

// Function BP_AIAction_WildLife.BP_AIAction_WildLife_C.ActionAbort
// (Event, Public, BlueprintEvent)
// Parameters:
// class APawn*                            ControlledPawn                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UBP_AIAction_WildLife_C::ActionAbort(class APawn* ControlledPawn)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AIAction_WildLife_C", "ActionAbort");

	Params::BP_AIAction_WildLife_C_ActionAbort Parms{};

	Parms.ControlledPawn = ControlledPawn;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_AIAction_WildLife.BP_AIAction_WildLife_C.ActionFinished
// (Event, Public, BlueprintEvent)
// Parameters:
// class APawn*                            ControlledPawn                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// EPawnActionResult                       WithResult                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_AIAction_WildLife_C::ActionFinished(class APawn* ControlledPawn, EPawnActionResult WithResult)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AIAction_WildLife_C", "ActionFinished");

	Params::BP_AIAction_WildLife_C_ActionFinished Parms{};

	Parms.ControlledPawn = ControlledPawn;
	Parms.WithResult = WithResult;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_AIAction_WildLife.BP_AIAction_WildLife_C.ActionPostTick
// (Event, Public, BlueprintEvent)
// Parameters:
// class APawn*                            ControlledPawn                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_AIAction_WildLife_C::ActionPostTick(class APawn* ControlledPawn, float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AIAction_WildLife_C", "ActionPostTick");

	Params::BP_AIAction_WildLife_C_ActionPostTick Parms{};

	Parms.ControlledPawn = ControlledPawn;
	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_AIAction_WildLife.BP_AIAction_WildLife_C.ActionTick
// (Event, Public, BlueprintEvent)
// Parameters:
// class APawn*                            ControlledPawn                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_AIAction_WildLife_C::ActionTick(class APawn* ControlledPawn, float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AIAction_WildLife_C", "ActionTick");

	Params::BP_AIAction_WildLife_C_ActionTick Parms{};

	Parms.ControlledPawn = ControlledPawn;
	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_AIAction_WildLife.BP_AIAction_WildLife_C.ActionTickAnyThread
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class APawn*                            ControlledPawn                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_AIAction_WildLife_C::ActionTickAnyThread(class APawn* ControlledPawn, float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AIAction_WildLife_C", "ActionTickAnyThread");

	Params::BP_AIAction_WildLife_C_ActionTickAnyThread Parms{};

	Parms.ControlledPawn = ControlledPawn;
	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_AIAction_WildLife.BP_AIAction_WildLife_C.ChangeNextMovePosition
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  Radius                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FVector                          CenterPos                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_AIAction_WildLife_C::ChangeNextMovePosition(double Radius, const struct FVector& CenterPos)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AIAction_WildLife_C", "ChangeNextMovePosition");

	Params::BP_AIAction_WildLife_C_ChangeNextMovePosition Parms{};

	Parms.Radius = Radius;
	Parms.CenterPos = std::move(CenterPos);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_AIAction_WildLife.BP_AIAction_WildLife_C.CheckDrinkWater_ForLeader
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ChangeState                                            (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_AIAction_WildLife_C::CheckDrinkWater_ForLeader(bool* ChangeState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AIAction_WildLife_C", "CheckDrinkWater_ForLeader");

	Params::BP_AIAction_WildLife_C_CheckDrinkWater_ForLeader Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (ChangeState != nullptr)
		*ChangeState = Parms.ChangeState;
}


// Function BP_AIAction_WildLife.BP_AIAction_WildLife_C.CheckDrinkWater_ForNotLeader
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ChangeAction                                           (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_AIAction_WildLife_C::CheckDrinkWater_ForNotLeader(bool* ChangeAction)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AIAction_WildLife_C", "CheckDrinkWater_ForNotLeader");

	Params::BP_AIAction_WildLife_C_CheckDrinkWater_ForNotLeader Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (ChangeAction != nullptr)
		*ChangeAction = Parms.ChangeAction;
}


// Function BP_AIAction_WildLife.BP_AIAction_WildLife_C.Event_StopFalse
// (BlueprintCallable, BlueprintEvent)

void UBP_AIAction_WildLife_C::Event_StopFalse()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AIAction_WildLife_C", "Event_StopFalse");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_AIAction_WildLife.BP_AIAction_WildLife_C.ExecuteUbergraph_BP_AIAction_WildLife
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_AIAction_WildLife_C::ExecuteUbergraph_BP_AIAction_WildLife(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AIAction_WildLife_C", "ExecuteUbergraph_BP_AIAction_WildLife");

	Params::BP_AIAction_WildLife_C_ExecuteUbergraph_BP_AIAction_WildLife Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_AIAction_WildLife.BP_AIAction_WildLife_C.FollowLeader
// (Public, BlueprintCallable, BlueprintEvent)

void UBP_AIAction_WildLife_C::FollowLeader()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AIAction_WildLife_C", "FollowLeader");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_AIAction_WildLife.BP_AIAction_WildLife_C.GetLeaderRestMode
// (Private, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool                                    Rest                                                   (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_AIAction_WildLife_C::GetLeaderRestMode(bool* Rest)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AIAction_WildLife_C", "GetLeaderRestMode");

	Params::BP_AIAction_WildLife_C_GetLeaderRestMode Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Rest != nullptr)
		*Rest = Parms.Rest;
}


// Function BP_AIAction_WildLife.BP_AIAction_WildLife_C.GetMyLocation
// (Private, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FVector                          NewParam                                               (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_AIAction_WildLife_C::GetMyLocation(struct FVector* NewParam)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AIAction_WildLife_C", "GetMyLocation");

	Params::BP_AIAction_WildLife_C_GetMyLocation Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (NewParam != nullptr)
		*NewParam = std::move(Parms.NewParam);
}


// Function BP_AIAction_WildLife.BP_AIAction_WildLife_C.IsSleepTime
// (Private, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool                                    Sleep                                                  (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_AIAction_WildLife_C::IsSleepTime(bool* Sleep)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AIAction_WildLife_C", "IsSleepTime");

	Params::BP_AIAction_WildLife_C_IsSleepTime Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Sleep != nullptr)
		*Sleep = Parms.Sleep;
}


// Function BP_AIAction_WildLife.BP_AIAction_WildLife_C.MoveAndAction
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// EPalActionType                          Action                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_AIAction_WildLife_C::MoveAndAction(EPalActionType Action)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AIAction_WildLife_C", "MoveAndAction");

	Params::BP_AIAction_WildLife_C_MoveAndAction Parms{};

	Parms.Action = Action;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_AIAction_WildLife.BP_AIAction_WildLife_C.OnFail_B707D59048A2C3D7CD1D13834143E5F8
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// EPathFollowingResult                    MovementResult                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_AIAction_WildLife_C::OnFail_B707D59048A2C3D7CD1D13834143E5F8(EPathFollowingResult MovementResult)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AIAction_WildLife_C", "OnFail_B707D59048A2C3D7CD1D13834143E5F8");

	Params::BP_AIAction_WildLife_C_OnFail_B707D59048A2C3D7CD1D13834143E5F8 Parms{};

	Parms.MovementResult = MovementResult;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_AIAction_WildLife.BP_AIAction_WildLife_C.OnFail_D878AC8F4430A5C3183029AD1B4F53CF
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// EPathFollowingResult                    MovementResult                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_AIAction_WildLife_C::OnFail_D878AC8F4430A5C3183029AD1B4F53CF(EPathFollowingResult MovementResult)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AIAction_WildLife_C", "OnFail_D878AC8F4430A5C3183029AD1B4F53CF");

	Params::BP_AIAction_WildLife_C_OnFail_D878AC8F4430A5C3183029AD1B4F53CF Parms{};

	Parms.MovementResult = MovementResult;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_AIAction_WildLife.BP_AIAction_WildLife_C.OnSuccess_B707D59048A2C3D7CD1D13834143E5F8
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// EPathFollowingResult                    MovementResult                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_AIAction_WildLife_C::OnSuccess_B707D59048A2C3D7CD1D13834143E5F8(EPathFollowingResult MovementResult)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AIAction_WildLife_C", "OnSuccess_B707D59048A2C3D7CD1D13834143E5F8");

	Params::BP_AIAction_WildLife_C_OnSuccess_B707D59048A2C3D7CD1D13834143E5F8 Parms{};

	Parms.MovementResult = MovementResult;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_AIAction_WildLife.BP_AIAction_WildLife_C.OnSuccess_D878AC8F4430A5C3183029AD1B4F53CF
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// EPathFollowingResult                    MovementResult                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_AIAction_WildLife_C::OnSuccess_D878AC8F4430A5C3183029AD1B4F53CF(EPathFollowingResult MovementResult)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AIAction_WildLife_C", "OnSuccess_D878AC8F4430A5C3183029AD1B4F53CF");

	Params::BP_AIAction_WildLife_C_OnSuccess_D878AC8F4430A5C3183029AD1B4F53CF Parms{};

	Parms.MovementResult = MovementResult;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_AIAction_WildLife.BP_AIAction_WildLife_C.PlayNightSleep
// (Private, HasDefaults, BlueprintCallable, BlueprintEvent)

void UBP_AIAction_WildLife_C::PlayNightSleep()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AIAction_WildLife_C", "PlayNightSleep");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_AIAction_WildLife.BP_AIAction_WildLife_C.RandomRestModeStart
// (Public, BlueprintCallable, BlueprintEvent)

void UBP_AIAction_WildLife_C::RandomRestModeStart()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AIAction_WildLife_C", "RandomRestModeStart");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_AIAction_WildLife.BP_AIAction_WildLife_C.ResetSelfAction
// (Public, BlueprintCallable, BlueprintEvent)

void UBP_AIAction_WildLife_C::ResetSelfAction()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AIAction_WildLife_C", "ResetSelfAction");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_AIAction_WildLife.BP_AIAction_WildLife_C.RestModeUpdate
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Nest                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_AIAction_WildLife_C::RestModeUpdate(bool Nest)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AIAction_WildLife_C", "RestModeUpdate");

	Params::BP_AIAction_WildLife_C_RestModeUpdate Parms{};

	Parms.Nest = Nest;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_AIAction_WildLife.BP_AIAction_WildLife_C.RestModeWalk
// (BlueprintCallable, BlueprintEvent)

void UBP_AIAction_WildLife_C::RestModeWalk()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AIAction_WildLife_C", "RestModeWalk");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_AIAction_WildLife.BP_AIAction_WildLife_C.SetDrinkWaterFlag
// (Public, BlueprintCallable, BlueprintEvent)

void UBP_AIAction_WildLife_C::SetDrinkWaterFlag()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AIAction_WildLife_C", "SetDrinkWaterFlag");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_AIAction_WildLife.BP_AIAction_WildLife_C.StateUpdate
// (Public, BlueprintCallable, BlueprintEvent)

void UBP_AIAction_WildLife_C::StateUpdate()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AIAction_WildLife_C", "StateUpdate");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_AIAction_WildLife.BP_AIAction_WildLife_C.«¹¿à¤ÙóÈ_Stack
// (BlueprintCallable, BlueprintEvent)

void UBP_AIAction_WildLife_C::_________Stack()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AIAction_WildLife_C", "«¹¿à¤ÙóÈ_Stack");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_AIAction_WildLife.BP_AIAction_WildLife_C.ActionPause
// (Event, Public, BlueprintEvent)
// Parameters:
// class APawn*                            ControlledPawn                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UBP_AIAction_WildLife_C::ActionPause(class APawn* ControlledPawn)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AIAction_WildLife_C", "ActionPause");

	Params::BP_AIAction_WildLife_C_ActionPause Parms{};

	Parms.ControlledPawn = ControlledPawn;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_AIAction_WildLife.BP_AIAction_WildLife_C.ActionResume
// (Event, Public, BlueprintEvent)
// Parameters:
// class APawn*                            ControlledPawn                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UBP_AIAction_WildLife_C::ActionResume(class APawn* ControlledPawn)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AIAction_WildLife_C", "ActionResume");

	Params::BP_AIAction_WildLife_C_ActionResume Parms{};

	Parms.ControlledPawn = ControlledPawn;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_AIAction_WildLife.BP_AIAction_WildLife_C.ActionStart
// (Event, Public, BlueprintEvent)
// Parameters:
// class APawn*                            ControlledPawn                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UBP_AIAction_WildLife_C::ActionStart(class APawn* ControlledPawn)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AIAction_WildLife_C", "ActionStart");

	Params::BP_AIAction_WildLife_C_ActionStart Parms{};

	Parms.ControlledPawn = ControlledPawn;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_AIAction_WildLife.BP_AIAction_WildLife_C.SoundEvent
// (Protected, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FVector                          EmitLocation                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_AIAction_WildLife_C::SoundEvent(const struct FVector& EmitLocation)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AIAction_WildLife_C", "SoundEvent");

	Params::BP_AIAction_WildLife_C_SoundEvent Parms{};

	Parms.EmitLocation = std::move(EmitLocation);

	UObject::ProcessEvent(Func, &Parms);
}

}

