#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PalCaptureJudgeObject

#include "Basic.hpp"

#include "BP_PalCaptureJudgeObject_classes.hpp"
#include "BP_PalCaptureJudgeObject_parameters.hpp"


namespace SDK
{

// Function BP_PalCaptureJudgeObject.BP_PalCaptureJudgeObject_C.ExecuteUbergraph_BP_PalCaptureJudgeObject
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_PalCaptureJudgeObject_C::ExecuteUbergraph_BP_PalCaptureJudgeObject(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PalCaptureJudgeObject_C", "ExecuteUbergraph_BP_PalCaptureJudgeObject");

	Params::BP_PalCaptureJudgeObject_C_ExecuteUbergraph_BP_PalCaptureJudgeObject Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_PalCaptureJudgeObject.BP_PalCaptureJudgeObject_C.OnCaptureSuccess
// (Event, Public, BlueprintEvent)
// Parameters:
// class APalCharacter*                    Character                                              (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// struct FCaptureResult                   Result                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_PalCaptureJudgeObject_C::OnCaptureSuccess(const class APalCharacter* Character, const struct FCaptureResult& Result)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PalCaptureJudgeObject_C", "OnCaptureSuccess");

	Params::BP_PalCaptureJudgeObject_C_OnCaptureSuccess Parms{};

	Parms.Character = Character;
	Parms.Result = std::move(Result);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_PalCaptureJudgeObject.BP_PalCaptureJudgeObject_C.OnFailedByMP
// (Event, Public, BlueprintEvent)
// Parameters:
// class APalCharacter*                    Character                                              (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// struct FCaptureResult                   Result                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_PalCaptureJudgeObject_C::OnFailedByMP(const class APalCharacter* Character, const struct FCaptureResult& Result)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PalCaptureJudgeObject_C", "OnFailedByMP");

	Params::BP_PalCaptureJudgeObject_C_OnFailedByMP Parms{};

	Parms.Character = Character;
	Parms.Result = std::move(Result);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_PalCaptureJudgeObject.BP_PalCaptureJudgeObject_C.OnFailedByTest
// (Event, Public, BlueprintEvent)
// Parameters:
// class APalCharacter*                    Character                                              (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// struct FCaptureResult                   Result                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_PalCaptureJudgeObject_C::OnFailedByTest(const class APalCharacter* Character, const struct FCaptureResult& Result)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PalCaptureJudgeObject_C", "OnFailedByTest");

	Params::BP_PalCaptureJudgeObject_C_OnFailedByTest Parms{};

	Parms.Character = Character;
	Parms.Result = std::move(Result);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_PalCaptureJudgeObject.BP_PalCaptureJudgeObject_C.OnFailedFinish
// (Event, Public, BlueprintEvent)

void ABP_PalCaptureJudgeObject_C::OnFailedFinish()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PalCaptureJudgeObject_C", "OnFailedFinish");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_PalCaptureJudgeObject.BP_PalCaptureJudgeObject_C.OnSuccessFinish
// (Event, Public, BlueprintEvent)

void ABP_PalCaptureJudgeObject_C::OnSuccessFinish()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PalCaptureJudgeObject_C", "OnSuccessFinish");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_PalCaptureJudgeObject.BP_PalCaptureJudgeObject_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_PalCaptureJudgeObject_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PalCaptureJudgeObject_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_PalCaptureJudgeObject.BP_PalCaptureJudgeObject_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_PalCaptureJudgeObject_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PalCaptureJudgeObject_C", "ReceiveTick");

	Params::BP_PalCaptureJudgeObject_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_PalCaptureJudgeObject.BP_PalCaptureJudgeObject_C.ReturnOwnerMovement
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  DeltaTime                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_PalCaptureJudgeObject_C::ReturnOwnerMovement(double DeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PalCaptureJudgeObject_C", "ReturnOwnerMovement");

	Params::BP_PalCaptureJudgeObject_C_ReturnOwnerMovement Parms{};

	Parms.DeltaTime = DeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}

}

