#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_RaidBossModeChangeEffect

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function BP_RaidBossModeChangeEffect.BP_RaidBossModeChangeEffect_C.ExecuteUbergraph_BP_RaidBossModeChangeEffect
// 0x0138 (0x0138 - 0x0000)
struct BP_RaidBossModeChangeEffect_C_ExecuteUbergraph_BP_RaidBossModeChangeEffect final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_43E1[0x4];                                     // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue;          // 0x0008(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_Event_DeltaSeconds;                         // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_43E2[0x4];                                     // 0x0024(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UPalSkeletalMeshComponent*              CallFunc_GetMainMesh_ReturnValue;                  // 0x0028(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_GetSocketLocation_ReturnValue;            // 0x0030(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             CallFunc_K2_SetActorLocation_SweepHitResult;       // 0x0048(0x00E8)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	bool                                          CallFunc_K2_SetActorLocation_ReturnValue;          // 0x0130(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_RaidBossModeChangeEffect_C_ExecuteUbergraph_BP_RaidBossModeChangeEffect) == 0x000008, "Wrong alignment on BP_RaidBossModeChangeEffect_C_ExecuteUbergraph_BP_RaidBossModeChangeEffect");
static_assert(sizeof(BP_RaidBossModeChangeEffect_C_ExecuteUbergraph_BP_RaidBossModeChangeEffect) == 0x000138, "Wrong size on BP_RaidBossModeChangeEffect_C_ExecuteUbergraph_BP_RaidBossModeChangeEffect");
static_assert(offsetof(BP_RaidBossModeChangeEffect_C_ExecuteUbergraph_BP_RaidBossModeChangeEffect, EntryPoint) == 0x000000, "Member 'BP_RaidBossModeChangeEffect_C_ExecuteUbergraph_BP_RaidBossModeChangeEffect::EntryPoint' has a wrong offset!");
static_assert(offsetof(BP_RaidBossModeChangeEffect_C_ExecuteUbergraph_BP_RaidBossModeChangeEffect, CallFunc_K2_GetActorLocation_ReturnValue) == 0x000008, "Member 'BP_RaidBossModeChangeEffect_C_ExecuteUbergraph_BP_RaidBossModeChangeEffect::CallFunc_K2_GetActorLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_RaidBossModeChangeEffect_C_ExecuteUbergraph_BP_RaidBossModeChangeEffect, K2Node_Event_DeltaSeconds) == 0x000020, "Member 'BP_RaidBossModeChangeEffect_C_ExecuteUbergraph_BP_RaidBossModeChangeEffect::K2Node_Event_DeltaSeconds' has a wrong offset!");
static_assert(offsetof(BP_RaidBossModeChangeEffect_C_ExecuteUbergraph_BP_RaidBossModeChangeEffect, CallFunc_GetMainMesh_ReturnValue) == 0x000028, "Member 'BP_RaidBossModeChangeEffect_C_ExecuteUbergraph_BP_RaidBossModeChangeEffect::CallFunc_GetMainMesh_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_RaidBossModeChangeEffect_C_ExecuteUbergraph_BP_RaidBossModeChangeEffect, CallFunc_GetSocketLocation_ReturnValue) == 0x000030, "Member 'BP_RaidBossModeChangeEffect_C_ExecuteUbergraph_BP_RaidBossModeChangeEffect::CallFunc_GetSocketLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_RaidBossModeChangeEffect_C_ExecuteUbergraph_BP_RaidBossModeChangeEffect, CallFunc_K2_SetActorLocation_SweepHitResult) == 0x000048, "Member 'BP_RaidBossModeChangeEffect_C_ExecuteUbergraph_BP_RaidBossModeChangeEffect::CallFunc_K2_SetActorLocation_SweepHitResult' has a wrong offset!");
static_assert(offsetof(BP_RaidBossModeChangeEffect_C_ExecuteUbergraph_BP_RaidBossModeChangeEffect, CallFunc_K2_SetActorLocation_ReturnValue) == 0x000130, "Member 'BP_RaidBossModeChangeEffect_C_ExecuteUbergraph_BP_RaidBossModeChangeEffect::CallFunc_K2_SetActorLocation_ReturnValue' has a wrong offset!");

// Function BP_RaidBossModeChangeEffect.BP_RaidBossModeChangeEffect_C.ReceiveTick
// 0x0004 (0x0004 - 0x0000)
struct BP_RaidBossModeChangeEffect_C_ReceiveTick final
{
public:
	float                                         DeltaSeconds;                                      // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_RaidBossModeChangeEffect_C_ReceiveTick) == 0x000004, "Wrong alignment on BP_RaidBossModeChangeEffect_C_ReceiveTick");
static_assert(sizeof(BP_RaidBossModeChangeEffect_C_ReceiveTick) == 0x000004, "Wrong size on BP_RaidBossModeChangeEffect_C_ReceiveTick");
static_assert(offsetof(BP_RaidBossModeChangeEffect_C_ReceiveTick, DeltaSeconds) == 0x000000, "Member 'BP_RaidBossModeChangeEffect_C_ReceiveTick::DeltaSeconds' has a wrong offset!");

// Function BP_RaidBossModeChangeEffect.BP_RaidBossModeChangeEffect_C.Set Target Pal
// 0x0008 (0x0008 - 0x0000)
struct BP_RaidBossModeChangeEffect_C_Set_Target_Pal final
{
public:
	class APalCharacter*                          Pal;                                               // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_RaidBossModeChangeEffect_C_Set_Target_Pal) == 0x000008, "Wrong alignment on BP_RaidBossModeChangeEffect_C_Set_Target_Pal");
static_assert(sizeof(BP_RaidBossModeChangeEffect_C_Set_Target_Pal) == 0x000008, "Wrong size on BP_RaidBossModeChangeEffect_C_Set_Target_Pal");
static_assert(offsetof(BP_RaidBossModeChangeEffect_C_Set_Target_Pal, Pal) == 0x000000, "Member 'BP_RaidBossModeChangeEffect_C_Set_Target_Pal::Pal' has a wrong offset!");

}

