#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_PalActionBar

#include "Basic.hpp"

#include "WBP_PalActionBar_classes.hpp"
#include "WBP_PalActionBar_parameters.hpp"


namespace SDK
{

// Function WBP_PalActionBar.WBP_PalActionBar_C.AnmEvent_Close
// (BlueprintCallable, BlueprintEvent)

void UWBP_PalActionBar_C::AnmEvent_Close()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PalActionBar_C", "AnmEvent_Close");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_PalActionBar.WBP_PalActionBar_C.AnmEvent_Open
// (BlueprintCallable, BlueprintEvent)

void UWBP_PalActionBar_C::AnmEvent_Open()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PalActionBar_C", "AnmEvent_Open");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_PalActionBar.WBP_PalActionBar_C.ExecuteUbergraph_WBP_PalActionBar
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_PalActionBar_C::ExecuteUbergraph_WBP_PalActionBar(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PalActionBar_C", "ExecuteUbergraph_WBP_PalActionBar");

	Params::WBP_PalActionBar_C_ExecuteUbergraph_WBP_PalActionBar Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_PalActionBar.WBP_PalActionBar_C.OnAddedAction
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_PalActionBar_C::OnAddedAction()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PalActionBar_C", "OnAddedAction");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_PalActionBar.WBP_PalActionBar_C.OnInitialized
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_PalActionBar_C::OnInitialized()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PalActionBar_C", "OnInitialized");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_PalActionBar.WBP_PalActionBar_C.OnRemovedAllAction
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_PalActionBar_C::OnRemovedAllAction()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PalActionBar_C", "OnRemovedAllAction");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_PalActionBar.WBP_PalActionBar_C.Tick
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// struct FGeometry                        MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// float                                   InDeltaTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_PalActionBar_C::Tick(const struct FGeometry& MyGeometry, float InDeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PalActionBar_C", "Tick");

	Params::WBP_PalActionBar_C_Tick Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InDeltaTime = InDeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}

}

