#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_MainMenu_Pal_Skill_Active

#include "Basic.hpp"

#include "Pal_structs.hpp"


namespace SDK::Params
{

// Function WBP_MainMenu_Pal_Skill_Active.WBP_MainMenu_Pal_Skill_Active_C.BndEvt__WBP_MainMenu_Pal_Skill_Active_WBP_PalInvisibleButton_K2Node_ComponentBoundEvent_0_CommonButtonBaseClicked__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct WBP_MainMenu_Pal_Skill_Active_C_BndEvt__WBP_MainMenu_Pal_Skill_Active_WBP_PalInvisibleButton_K2Node_ComponentBoundEvent_0_CommonButtonBaseClicked__DelegateSignature final
{
public:
	class UCommonButtonBase*                      Button;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_MainMenu_Pal_Skill_Active_C_BndEvt__WBP_MainMenu_Pal_Skill_Active_WBP_PalInvisibleButton_K2Node_ComponentBoundEvent_0_CommonButtonBaseClicked__DelegateSignature) == 0x000008, "Wrong alignment on WBP_MainMenu_Pal_Skill_Active_C_BndEvt__WBP_MainMenu_Pal_Skill_Active_WBP_PalInvisibleButton_K2Node_ComponentBoundEvent_0_CommonButtonBaseClicked__DelegateSignature");
static_assert(sizeof(WBP_MainMenu_Pal_Skill_Active_C_BndEvt__WBP_MainMenu_Pal_Skill_Active_WBP_PalInvisibleButton_K2Node_ComponentBoundEvent_0_CommonButtonBaseClicked__DelegateSignature) == 0x000008, "Wrong size on WBP_MainMenu_Pal_Skill_Active_C_BndEvt__WBP_MainMenu_Pal_Skill_Active_WBP_PalInvisibleButton_K2Node_ComponentBoundEvent_0_CommonButtonBaseClicked__DelegateSignature");
static_assert(offsetof(WBP_MainMenu_Pal_Skill_Active_C_BndEvt__WBP_MainMenu_Pal_Skill_Active_WBP_PalInvisibleButton_K2Node_ComponentBoundEvent_0_CommonButtonBaseClicked__DelegateSignature, Button) == 0x000000, "Member 'WBP_MainMenu_Pal_Skill_Active_C_BndEvt__WBP_MainMenu_Pal_Skill_Active_WBP_PalInvisibleButton_K2Node_ComponentBoundEvent_0_CommonButtonBaseClicked__DelegateSignature::Button' has a wrong offset!");

// Function WBP_MainMenu_Pal_Skill_Active.WBP_MainMenu_Pal_Skill_Active_C.BndEvt__WBP_MainMenu_Pal_Skill_Active_WBP_PalInvisibleButton_K2Node_ComponentBoundEvent_4_CommonButtonBaseClicked__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct WBP_MainMenu_Pal_Skill_Active_C_BndEvt__WBP_MainMenu_Pal_Skill_Active_WBP_PalInvisibleButton_K2Node_ComponentBoundEvent_4_CommonButtonBaseClicked__DelegateSignature final
{
public:
	class UCommonButtonBase*                      Button;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_MainMenu_Pal_Skill_Active_C_BndEvt__WBP_MainMenu_Pal_Skill_Active_WBP_PalInvisibleButton_K2Node_ComponentBoundEvent_4_CommonButtonBaseClicked__DelegateSignature) == 0x000008, "Wrong alignment on WBP_MainMenu_Pal_Skill_Active_C_BndEvt__WBP_MainMenu_Pal_Skill_Active_WBP_PalInvisibleButton_K2Node_ComponentBoundEvent_4_CommonButtonBaseClicked__DelegateSignature");
static_assert(sizeof(WBP_MainMenu_Pal_Skill_Active_C_BndEvt__WBP_MainMenu_Pal_Skill_Active_WBP_PalInvisibleButton_K2Node_ComponentBoundEvent_4_CommonButtonBaseClicked__DelegateSignature) == 0x000008, "Wrong size on WBP_MainMenu_Pal_Skill_Active_C_BndEvt__WBP_MainMenu_Pal_Skill_Active_WBP_PalInvisibleButton_K2Node_ComponentBoundEvent_4_CommonButtonBaseClicked__DelegateSignature");
static_assert(offsetof(WBP_MainMenu_Pal_Skill_Active_C_BndEvt__WBP_MainMenu_Pal_Skill_Active_WBP_PalInvisibleButton_K2Node_ComponentBoundEvent_4_CommonButtonBaseClicked__DelegateSignature, Button) == 0x000000, "Member 'WBP_MainMenu_Pal_Skill_Active_C_BndEvt__WBP_MainMenu_Pal_Skill_Active_WBP_PalInvisibleButton_K2Node_ComponentBoundEvent_4_CommonButtonBaseClicked__DelegateSignature::Button' has a wrong offset!");

// Function WBP_MainMenu_Pal_Skill_Active.WBP_MainMenu_Pal_Skill_Active_C.BndEvt__WBP_MainMenu_Pal_Skill_Active_WBP_PalInvisibleButton_K2Node_ComponentBoundEvent_5_CommonButtonBaseClicked__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct WBP_MainMenu_Pal_Skill_Active_C_BndEvt__WBP_MainMenu_Pal_Skill_Active_WBP_PalInvisibleButton_K2Node_ComponentBoundEvent_5_CommonButtonBaseClicked__DelegateSignature final
{
public:
	class UCommonButtonBase*                      Button;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_MainMenu_Pal_Skill_Active_C_BndEvt__WBP_MainMenu_Pal_Skill_Active_WBP_PalInvisibleButton_K2Node_ComponentBoundEvent_5_CommonButtonBaseClicked__DelegateSignature) == 0x000008, "Wrong alignment on WBP_MainMenu_Pal_Skill_Active_C_BndEvt__WBP_MainMenu_Pal_Skill_Active_WBP_PalInvisibleButton_K2Node_ComponentBoundEvent_5_CommonButtonBaseClicked__DelegateSignature");
static_assert(sizeof(WBP_MainMenu_Pal_Skill_Active_C_BndEvt__WBP_MainMenu_Pal_Skill_Active_WBP_PalInvisibleButton_K2Node_ComponentBoundEvent_5_CommonButtonBaseClicked__DelegateSignature) == 0x000008, "Wrong size on WBP_MainMenu_Pal_Skill_Active_C_BndEvt__WBP_MainMenu_Pal_Skill_Active_WBP_PalInvisibleButton_K2Node_ComponentBoundEvent_5_CommonButtonBaseClicked__DelegateSignature");
static_assert(offsetof(WBP_MainMenu_Pal_Skill_Active_C_BndEvt__WBP_MainMenu_Pal_Skill_Active_WBP_PalInvisibleButton_K2Node_ComponentBoundEvent_5_CommonButtonBaseClicked__DelegateSignature, Button) == 0x000000, "Member 'WBP_MainMenu_Pal_Skill_Active_C_BndEvt__WBP_MainMenu_Pal_Skill_Active_WBP_PalInvisibleButton_K2Node_ComponentBoundEvent_5_CommonButtonBaseClicked__DelegateSignature::Button' has a wrong offset!");

// Function WBP_MainMenu_Pal_Skill_Active.WBP_MainMenu_Pal_Skill_Active_C.ExecuteUbergraph_WBP_MainMenu_Pal_Skill_Active
// 0x0020 (0x0020 - 0x0000)
struct WBP_MainMenu_Pal_Skill_Active_C_ExecuteUbergraph_WBP_MainMenu_Pal_Skill_Active final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4031[0x4];                                     // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UCommonButtonBase*                      K2Node_ComponentBoundEvent_Button_2;               // 0x0008(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UCommonButtonBase*                      K2Node_ComponentBoundEvent_Button_1;               // 0x0010(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UCommonButtonBase*                      K2Node_ComponentBoundEvent_Button;                 // 0x0018(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_MainMenu_Pal_Skill_Active_C_ExecuteUbergraph_WBP_MainMenu_Pal_Skill_Active) == 0x000008, "Wrong alignment on WBP_MainMenu_Pal_Skill_Active_C_ExecuteUbergraph_WBP_MainMenu_Pal_Skill_Active");
static_assert(sizeof(WBP_MainMenu_Pal_Skill_Active_C_ExecuteUbergraph_WBP_MainMenu_Pal_Skill_Active) == 0x000020, "Wrong size on WBP_MainMenu_Pal_Skill_Active_C_ExecuteUbergraph_WBP_MainMenu_Pal_Skill_Active");
static_assert(offsetof(WBP_MainMenu_Pal_Skill_Active_C_ExecuteUbergraph_WBP_MainMenu_Pal_Skill_Active, EntryPoint) == 0x000000, "Member 'WBP_MainMenu_Pal_Skill_Active_C_ExecuteUbergraph_WBP_MainMenu_Pal_Skill_Active::EntryPoint' has a wrong offset!");
static_assert(offsetof(WBP_MainMenu_Pal_Skill_Active_C_ExecuteUbergraph_WBP_MainMenu_Pal_Skill_Active, K2Node_ComponentBoundEvent_Button_2) == 0x000008, "Member 'WBP_MainMenu_Pal_Skill_Active_C_ExecuteUbergraph_WBP_MainMenu_Pal_Skill_Active::K2Node_ComponentBoundEvent_Button_2' has a wrong offset!");
static_assert(offsetof(WBP_MainMenu_Pal_Skill_Active_C_ExecuteUbergraph_WBP_MainMenu_Pal_Skill_Active, K2Node_ComponentBoundEvent_Button_1) == 0x000010, "Member 'WBP_MainMenu_Pal_Skill_Active_C_ExecuteUbergraph_WBP_MainMenu_Pal_Skill_Active::K2Node_ComponentBoundEvent_Button_1' has a wrong offset!");
static_assert(offsetof(WBP_MainMenu_Pal_Skill_Active_C_ExecuteUbergraph_WBP_MainMenu_Pal_Skill_Active, K2Node_ComponentBoundEvent_Button) == 0x000018, "Member 'WBP_MainMenu_Pal_Skill_Active_C_ExecuteUbergraph_WBP_MainMenu_Pal_Skill_Active::K2Node_ComponentBoundEvent_Button' has a wrong offset!");

// Function WBP_MainMenu_Pal_Skill_Active.WBP_MainMenu_Pal_Skill_Active_C.GetBindedWazaID
// 0x0001 (0x0001 - 0x0000)
struct WBP_MainMenu_Pal_Skill_Active_C_GetBindedWazaID final
{
public:
	EPalWazaID                                    WazaID;                                            // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_MainMenu_Pal_Skill_Active_C_GetBindedWazaID) == 0x000001, "Wrong alignment on WBP_MainMenu_Pal_Skill_Active_C_GetBindedWazaID");
static_assert(sizeof(WBP_MainMenu_Pal_Skill_Active_C_GetBindedWazaID) == 0x000001, "Wrong size on WBP_MainMenu_Pal_Skill_Active_C_GetBindedWazaID");
static_assert(offsetof(WBP_MainMenu_Pal_Skill_Active_C_GetBindedWazaID, WazaID) == 0x000000, "Member 'WBP_MainMenu_Pal_Skill_Active_C_GetBindedWazaID::WazaID' has a wrong offset!");

// Function WBP_MainMenu_Pal_Skill_Active.WBP_MainMenu_Pal_Skill_Active_C.OnClicked__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct WBP_MainMenu_Pal_Skill_Active_C_OnClicked__DelegateSignature final
{
public:
	class UWBP_MainMenu_Pal_Skill_Active_C*       SelfWidget;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_MainMenu_Pal_Skill_Active_C_OnClicked__DelegateSignature) == 0x000008, "Wrong alignment on WBP_MainMenu_Pal_Skill_Active_C_OnClicked__DelegateSignature");
static_assert(sizeof(WBP_MainMenu_Pal_Skill_Active_C_OnClicked__DelegateSignature) == 0x000008, "Wrong size on WBP_MainMenu_Pal_Skill_Active_C_OnClicked__DelegateSignature");
static_assert(offsetof(WBP_MainMenu_Pal_Skill_Active_C_OnClicked__DelegateSignature, SelfWidget) == 0x000000, "Member 'WBP_MainMenu_Pal_Skill_Active_C_OnClicked__DelegateSignature::SelfWidget' has a wrong offset!");

// Function WBP_MainMenu_Pal_Skill_Active.WBP_MainMenu_Pal_Skill_Active_C.OnHovered__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct WBP_MainMenu_Pal_Skill_Active_C_OnHovered__DelegateSignature final
{
public:
	class UWBP_MainMenu_Pal_Skill_Active_C*       SelfWidget;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_MainMenu_Pal_Skill_Active_C_OnHovered__DelegateSignature) == 0x000008, "Wrong alignment on WBP_MainMenu_Pal_Skill_Active_C_OnHovered__DelegateSignature");
static_assert(sizeof(WBP_MainMenu_Pal_Skill_Active_C_OnHovered__DelegateSignature) == 0x000008, "Wrong size on WBP_MainMenu_Pal_Skill_Active_C_OnHovered__DelegateSignature");
static_assert(offsetof(WBP_MainMenu_Pal_Skill_Active_C_OnHovered__DelegateSignature, SelfWidget) == 0x000000, "Member 'WBP_MainMenu_Pal_Skill_Active_C_OnHovered__DelegateSignature::SelfWidget' has a wrong offset!");

// Function WBP_MainMenu_Pal_Skill_Active.WBP_MainMenu_Pal_Skill_Active_C.OnUnhovered__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct WBP_MainMenu_Pal_Skill_Active_C_OnUnhovered__DelegateSignature final
{
public:
	class UWBP_MainMenu_Pal_Skill_Active_C*       SelfWidget;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_MainMenu_Pal_Skill_Active_C_OnUnhovered__DelegateSignature) == 0x000008, "Wrong alignment on WBP_MainMenu_Pal_Skill_Active_C_OnUnhovered__DelegateSignature");
static_assert(sizeof(WBP_MainMenu_Pal_Skill_Active_C_OnUnhovered__DelegateSignature) == 0x000008, "Wrong size on WBP_MainMenu_Pal_Skill_Active_C_OnUnhovered__DelegateSignature");
static_assert(offsetof(WBP_MainMenu_Pal_Skill_Active_C_OnUnhovered__DelegateSignature, SelfWidget) == 0x000000, "Member 'WBP_MainMenu_Pal_Skill_Active_C_OnUnhovered__DelegateSignature::SelfWidget' has a wrong offset!");

// Function WBP_MainMenu_Pal_Skill_Active.WBP_MainMenu_Pal_Skill_Active_C.SetEmptyInfo
// 0x0018 (0x0018 - 0x0000)
struct WBP_MainMenu_Pal_Skill_Active_C_SetEmptyInfo final
{
public:
	class FText                                   CallFunc_GetLocalizedTextFromHandle_Text;          // 0x0000(0x0018)()
};
static_assert(alignof(WBP_MainMenu_Pal_Skill_Active_C_SetEmptyInfo) == 0x000008, "Wrong alignment on WBP_MainMenu_Pal_Skill_Active_C_SetEmptyInfo");
static_assert(sizeof(WBP_MainMenu_Pal_Skill_Active_C_SetEmptyInfo) == 0x000018, "Wrong size on WBP_MainMenu_Pal_Skill_Active_C_SetEmptyInfo");
static_assert(offsetof(WBP_MainMenu_Pal_Skill_Active_C_SetEmptyInfo, CallFunc_GetLocalizedTextFromHandle_Text) == 0x000000, "Member 'WBP_MainMenu_Pal_Skill_Active_C_SetEmptyInfo::CallFunc_GetLocalizedTextFromHandle_Text' has a wrong offset!");

// Function WBP_MainMenu_Pal_Skill_Active.WBP_MainMenu_Pal_Skill_Active_C.SetWazaID
// 0x00D0 (0x00D0 - 0x0000)
struct WBP_MainMenu_Pal_Skill_Active_C_SetWazaID final
{
public:
	EPalWazaID                                    WazaID;                                            // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4032[0x7];                                     // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_GetWazaName_outName;                      // 0x0008(0x0018)()
	class UPalWazaDatabase*                       CallFunc_GetWazaDatabase_ReturnValue;              // 0x0020(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FPalWazaDatabaseRaw                    CallFunc_FindWazaForBP_OutData;                    // 0x0028(0x0050)()
	bool                                          CallFunc_FindWazaForBP_ReturnValue;                // 0x0078(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4033[0x7];                                     // 0x0079(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TSoftObjectPtr<class UTexture2D>              CallFunc_Map_Find_Value;                           // 0x0080(0x0030)(HasGetValueTypeHash)
	bool                                          CallFunc_Map_Find_ReturnValue;                     // 0x00B0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4034[0x7];                                     // 0x00B1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_Conv_IntToText_ReturnValue;               // 0x00B8(0x0018)()
};
static_assert(alignof(WBP_MainMenu_Pal_Skill_Active_C_SetWazaID) == 0x000008, "Wrong alignment on WBP_MainMenu_Pal_Skill_Active_C_SetWazaID");
static_assert(sizeof(WBP_MainMenu_Pal_Skill_Active_C_SetWazaID) == 0x0000D0, "Wrong size on WBP_MainMenu_Pal_Skill_Active_C_SetWazaID");
static_assert(offsetof(WBP_MainMenu_Pal_Skill_Active_C_SetWazaID, WazaID) == 0x000000, "Member 'WBP_MainMenu_Pal_Skill_Active_C_SetWazaID::WazaID' has a wrong offset!");
static_assert(offsetof(WBP_MainMenu_Pal_Skill_Active_C_SetWazaID, CallFunc_GetWazaName_outName) == 0x000008, "Member 'WBP_MainMenu_Pal_Skill_Active_C_SetWazaID::CallFunc_GetWazaName_outName' has a wrong offset!");
static_assert(offsetof(WBP_MainMenu_Pal_Skill_Active_C_SetWazaID, CallFunc_GetWazaDatabase_ReturnValue) == 0x000020, "Member 'WBP_MainMenu_Pal_Skill_Active_C_SetWazaID::CallFunc_GetWazaDatabase_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_MainMenu_Pal_Skill_Active_C_SetWazaID, CallFunc_FindWazaForBP_OutData) == 0x000028, "Member 'WBP_MainMenu_Pal_Skill_Active_C_SetWazaID::CallFunc_FindWazaForBP_OutData' has a wrong offset!");
static_assert(offsetof(WBP_MainMenu_Pal_Skill_Active_C_SetWazaID, CallFunc_FindWazaForBP_ReturnValue) == 0x000078, "Member 'WBP_MainMenu_Pal_Skill_Active_C_SetWazaID::CallFunc_FindWazaForBP_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_MainMenu_Pal_Skill_Active_C_SetWazaID, CallFunc_Map_Find_Value) == 0x000080, "Member 'WBP_MainMenu_Pal_Skill_Active_C_SetWazaID::CallFunc_Map_Find_Value' has a wrong offset!");
static_assert(offsetof(WBP_MainMenu_Pal_Skill_Active_C_SetWazaID, CallFunc_Map_Find_ReturnValue) == 0x0000B0, "Member 'WBP_MainMenu_Pal_Skill_Active_C_SetWazaID::CallFunc_Map_Find_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_MainMenu_Pal_Skill_Active_C_SetWazaID, CallFunc_Conv_IntToText_ReturnValue) == 0x0000B8, "Member 'WBP_MainMenu_Pal_Skill_Active_C_SetWazaID::CallFunc_Conv_IntToText_ReturnValue' has a wrong offset!");

}

