#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_MainMenu_Pal_Skill_Active

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Pal_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_MainMenu_Pal_Skill_Active.WBP_MainMenu_Pal_Skill_Active_C
// 0x0110 (0x0388 - 0x0278)
class UWBP_MainMenu_Pal_Skill_Active_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0278(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       Anim_Empty;                                        // 0x0280(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       Anm_NormalToFocus;                                 // 0x0288(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       Anm_Click;                                         // 0x0290(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       Anm_Focus;                                         // 0x0298(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       Anm_Normal;                                        // 0x02A0(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UImage*                                 Image_58;                                          // 0x02A8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_Element;                                     // 0x02B0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_Selected;                                    // 0x02B8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_Selected_1;                                  // 0x02C0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 SkillBase;                                         // 0x02C8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBP_PalTextBlock_C*                     Text_WazaName;                                     // 0x02D0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBP_PalTextBlock_C*                     Text_WazaPower;                                    // 0x02D8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_MainMenu_Cursor_C*                 WBP_MainMenu_Cursor;                               // 0x02E0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_PalInvisibleButton_C*              WBP_PalInvisibleButton;                            // 0x02E8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	FMulticastInlineDelegateProperty_             OnHovered;                                         // 0x02F0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	FMulticastInlineDelegateProperty_             OnUnhovered;                                       // 0x0300(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	EPalWazaID                                    BindedWazaID;                                      // 0x0310(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4030[0x7];                                     // 0x0311(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	FMulticastInlineDelegateProperty_             OnClicked;                                         // 0x0318(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TMap<EPalElementType, TSoftObjectPtr<class UTexture2D>> ElementTextureMap;                                 // 0x0328(0x0050)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FDataTableRowHandle                    EmptySlotMsgID;                                    // 0x0378(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor)

public:
	void AnmEvent_Selected();
	void AnmEvent_Unselcted();
	void BndEvt__WBP_MainMenu_Pal_Skill_Active_WBP_PalInvisibleButton_K2Node_ComponentBoundEvent_0_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button);
	void BndEvt__WBP_MainMenu_Pal_Skill_Active_WBP_PalInvisibleButton_K2Node_ComponentBoundEvent_4_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button);
	void BndEvt__WBP_MainMenu_Pal_Skill_Active_WBP_PalInvisibleButton_K2Node_ComponentBoundEvent_5_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button);
	void Clear();
	void Construct();
	void ExecuteUbergraph_WBP_MainMenu_Pal_Skill_Active(int32 EntryPoint);
	void GetBindedWazaID(EPalWazaID* WazaID);
	void OnClicked__DelegateSignature(class UWBP_MainMenu_Pal_Skill_Active_C* SelfWidget);
	void OnHovered__DelegateSignature(class UWBP_MainMenu_Pal_Skill_Active_C* SelfWidget);
	void OnUnhovered__DelegateSignature(class UWBP_MainMenu_Pal_Skill_Active_C* SelfWidget);
	void SetEmptyInfo();
	void SetWazaID(EPalWazaID WazaID);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_MainMenu_Pal_Skill_Active_C">();
	}
	static class UWBP_MainMenu_Pal_Skill_Active_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_MainMenu_Pal_Skill_Active_C>();
	}
};
static_assert(alignof(UWBP_MainMenu_Pal_Skill_Active_C) == 0x000008, "Wrong alignment on UWBP_MainMenu_Pal_Skill_Active_C");
static_assert(sizeof(UWBP_MainMenu_Pal_Skill_Active_C) == 0x000388, "Wrong size on UWBP_MainMenu_Pal_Skill_Active_C");
static_assert(offsetof(UWBP_MainMenu_Pal_Skill_Active_C, UberGraphFrame) == 0x000278, "Member 'UWBP_MainMenu_Pal_Skill_Active_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_Skill_Active_C, Anim_Empty) == 0x000280, "Member 'UWBP_MainMenu_Pal_Skill_Active_C::Anim_Empty' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_Skill_Active_C, Anm_NormalToFocus) == 0x000288, "Member 'UWBP_MainMenu_Pal_Skill_Active_C::Anm_NormalToFocus' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_Skill_Active_C, Anm_Click) == 0x000290, "Member 'UWBP_MainMenu_Pal_Skill_Active_C::Anm_Click' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_Skill_Active_C, Anm_Focus) == 0x000298, "Member 'UWBP_MainMenu_Pal_Skill_Active_C::Anm_Focus' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_Skill_Active_C, Anm_Normal) == 0x0002A0, "Member 'UWBP_MainMenu_Pal_Skill_Active_C::Anm_Normal' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_Skill_Active_C, Image_58) == 0x0002A8, "Member 'UWBP_MainMenu_Pal_Skill_Active_C::Image_58' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_Skill_Active_C, Image_Element) == 0x0002B0, "Member 'UWBP_MainMenu_Pal_Skill_Active_C::Image_Element' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_Skill_Active_C, Image_Selected) == 0x0002B8, "Member 'UWBP_MainMenu_Pal_Skill_Active_C::Image_Selected' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_Skill_Active_C, Image_Selected_1) == 0x0002C0, "Member 'UWBP_MainMenu_Pal_Skill_Active_C::Image_Selected_1' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_Skill_Active_C, SkillBase) == 0x0002C8, "Member 'UWBP_MainMenu_Pal_Skill_Active_C::SkillBase' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_Skill_Active_C, Text_WazaName) == 0x0002D0, "Member 'UWBP_MainMenu_Pal_Skill_Active_C::Text_WazaName' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_Skill_Active_C, Text_WazaPower) == 0x0002D8, "Member 'UWBP_MainMenu_Pal_Skill_Active_C::Text_WazaPower' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_Skill_Active_C, WBP_MainMenu_Cursor) == 0x0002E0, "Member 'UWBP_MainMenu_Pal_Skill_Active_C::WBP_MainMenu_Cursor' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_Skill_Active_C, WBP_PalInvisibleButton) == 0x0002E8, "Member 'UWBP_MainMenu_Pal_Skill_Active_C::WBP_PalInvisibleButton' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_Skill_Active_C, OnHovered) == 0x0002F0, "Member 'UWBP_MainMenu_Pal_Skill_Active_C::OnHovered' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_Skill_Active_C, OnUnhovered) == 0x000300, "Member 'UWBP_MainMenu_Pal_Skill_Active_C::OnUnhovered' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_Skill_Active_C, BindedWazaID) == 0x000310, "Member 'UWBP_MainMenu_Pal_Skill_Active_C::BindedWazaID' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_Skill_Active_C, OnClicked) == 0x000318, "Member 'UWBP_MainMenu_Pal_Skill_Active_C::OnClicked' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_Skill_Active_C, ElementTextureMap) == 0x000328, "Member 'UWBP_MainMenu_Pal_Skill_Active_C::ElementTextureMap' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_Skill_Active_C, EmptySlotMsgID) == 0x000378, "Member 'UWBP_MainMenu_Pal_Skill_Active_C::EmptySlotMsgID' has a wrong offset!");

}

