#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_PalInGameMenuItemIcon

#include "Basic.hpp"

#include "WBP_PalInGameMenuItemIcon_classes.hpp"
#include "WBP_PalInGameMenuItemIcon_parameters.hpp"


namespace SDK
{

// Function WBP_PalInGameMenuItemIcon.WBP_PalInGameMenuItemIcon_C.EmptyEvent
// (BlueprintCallable, BlueprintEvent)

void UWBP_PalInGameMenuItemIcon_C::EmptyEvent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PalInGameMenuItemIcon_C", "EmptyEvent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_PalInGameMenuItemIcon.WBP_PalInGameMenuItemIcon_C.ExecuteUbergraph_WBP_PalInGameMenuItemIcon
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_PalInGameMenuItemIcon_C::ExecuteUbergraph_WBP_PalInGameMenuItemIcon(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PalInGameMenuItemIcon_C", "ExecuteUbergraph_WBP_PalInGameMenuItemIcon");

	Params::WBP_PalInGameMenuItemIcon_C_ExecuteUbergraph_WBP_PalInGameMenuItemIcon Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_PalInGameMenuItemIcon.WBP_PalInGameMenuItemIcon_C.LoadedTextureEvent
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UTexture2D*                       LoadedTexture                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_PalInGameMenuItemIcon_C::LoadedTextureEvent(class UTexture2D* LoadedTexture)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PalInGameMenuItemIcon_C", "LoadedTextureEvent");

	Params::WBP_PalInGameMenuItemIcon_C_LoadedTextureEvent Parms{};

	Parms.LoadedTexture = LoadedTexture;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_PalInGameMenuItemIcon.WBP_PalInGameMenuItemIcon_C.OnInitialized
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_PalInGameMenuItemIcon_C::OnInitialized()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PalInGameMenuItemIcon_C", "OnInitialized");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_PalInGameMenuItemIcon.WBP_PalInGameMenuItemIcon_C.StartLoadEvent
// (BlueprintCallable, BlueprintEvent)

void UWBP_PalInGameMenuItemIcon_C::StartLoadEvent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PalInGameMenuItemIcon_C", "StartLoadEvent");

	UObject::ProcessEvent(Func, nullptr);
}

}

